package crte.com.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import crte.com.radio.entry.Contact;
import crte.com.radio.entry.Message;
import crte.com.radio.entry.Voice;
import crte.com.radio.entry.Work;
import crte.com.radio.entry.Zone;

import crte.com.greendao.ContactDao;
import crte.com.greendao.MessageDao;
import crte.com.greendao.VoiceDao;
import crte.com.greendao.WorkDao;
import crte.com.greendao.ZoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig voiceDaoConfig;
    private final DaoConfig workDaoConfig;
    private final DaoConfig zoneDaoConfig;

    private final ContactDao contactDao;
    private final MessageDao messageDao;
    private final VoiceDao voiceDao;
    private final WorkDao workDao;
    private final ZoneDao zoneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        voiceDaoConfig = daoConfigMap.get(VoiceDao.class).clone();
        voiceDaoConfig.initIdentityScope(type);

        workDaoConfig = daoConfigMap.get(WorkDao.class).clone();
        workDaoConfig.initIdentityScope(type);

        zoneDaoConfig = daoConfigMap.get(ZoneDao.class).clone();
        zoneDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        voiceDao = new VoiceDao(voiceDaoConfig, this);
        workDao = new WorkDao(workDaoConfig, this);
        zoneDao = new ZoneDao(zoneDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(Message.class, messageDao);
        registerDao(Voice.class, voiceDao);
        registerDao(Work.class, workDao);
        registerDao(Zone.class, zoneDao);
    }
    
    public void clear() {
        contactDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        voiceDaoConfig.clearIdentityScope();
        workDaoConfig.clearIdentityScope();
        zoneDaoConfig.clearIdentityScope();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public VoiceDao getVoiceDao() {
        return voiceDao;
    }

    public WorkDao getWorkDao() {
        return workDao;
    }

    public ZoneDao getZoneDao() {
        return zoneDao;
    }

}
