package crte.com.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import crte.com.radio.entry.Voice;
import crte.com.radio.entry.Work;
import crte.com.radio.entry.ContactDb;

import crte.com.greendao.VoiceDao;
import crte.com.greendao.WorkDao;
import crte.com.greendao.ContactDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig voiceDaoConfig;
    private final DaoConfig workDaoConfig;
    private final DaoConfig contactDbDaoConfig;

    private final VoiceDao voiceDao;
    private final WorkDao workDao;
    private final ContactDbDao contactDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        voiceDaoConfig = daoConfigMap.get(VoiceDao.class).clone();
        voiceDaoConfig.initIdentityScope(type);

        workDaoConfig = daoConfigMap.get(WorkDao.class).clone();
        workDaoConfig.initIdentityScope(type);

        contactDbDaoConfig = daoConfigMap.get(ContactDbDao.class).clone();
        contactDbDaoConfig.initIdentityScope(type);

        voiceDao = new VoiceDao(voiceDaoConfig, this);
        workDao = new WorkDao(workDaoConfig, this);
        contactDbDao = new ContactDbDao(contactDbDaoConfig, this);

        registerDao(Voice.class, voiceDao);
        registerDao(Work.class, workDao);
        registerDao(ContactDb.class, contactDbDao);
    }
    
    public void clear() {
        voiceDaoConfig.clearIdentityScope();
        workDaoConfig.clearIdentityScope();
        contactDbDaoConfig.clearIdentityScope();
    }

    public VoiceDao getVoiceDao() {
        return voiceDao;
    }

    public WorkDao getWorkDao() {
        return workDao;
    }

    public ContactDbDao getContactDbDao() {
        return contactDbDao;
    }

}
